language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: required

before_install:
  - "chmod +x gradlew"
  - "sudo apt-get update"
  - "./gradlew wrapper"

script:
  - "./gradlew check"
  - "./gradlew assemble"